obj-y                                       += resources/
obj-y                                       += fih_projects.o

obj-$(CONFIG_FIH_PROJECT_GOX)               += gox/
obj-$(CONFIG_FIH_PROJECT_GO9)               += go9/
